2024/08/22 09:49:09 main.go:42: failed to connect to `host=localhost user=ayo database=pickitup_db3`: tls error (server refused TLS connection)
2024/08/22 09:50:14 main.go:42: Failed to connect to database: failed to connect to `host=localhost user=ayo database=pickitup_db3`: tls error (server refused TLS connection)
2024/08/22 09:51:12 db.go:15: Database Connected Successfully!
2024/08/22 10:05:33 db.go:15: Database Connected Successfully!
2024/08/22 10:55:09 db.go:15: Database Connected Successfully!
2024/08/22 10:58:56 db.go:15: Database Connected Successfully!
2024/08/22 15:09:35 db.go:15: Database Connected Successfully!
2024/08/22 15:13:08 db.go:15: Database Connected Successfully!
2024/08/22 15:13:12 user_controller.go:30: invalid character '"' after object key:value pair
2024/08/22 15:14:39 db.go:15: Database Connected Successfully!
2024/08/22 15:16:18 db.go:15: Database Connected Successfully!
2024/08/22 15:17:50 db.go:15: Database Connected Successfully!
2024/08/22 15:17:53 user_controller.go:37: user with this email already exists
2024/08/22 15:20:05 db.go:15: Database Connected Successfully!
2024/08/22 15:21:13 user_controller.go:38: user with this email already exists
2024/08/22 15:22:41 db.go:15: Database Connected Successfully!
2024/08/22 15:23:38 user_controller.go:38: user with this email already exists
2024/08/22 15:25:48 db.go:15: Database Connected Successfully!
